# Generated by Django 3.1.5 on 2021-01-31 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название направления')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название реагента')),
                ('text', models.TextField(verbose_name='Описание реагента')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.division', verbose_name='Выбрать направление')),
            ],
            options={
                'verbose_name': 'Реагент',
                'verbose_name_plural': 'Реагенты',
            },
        ),
    ]
