# Generated by Django 3.1.5 on 2021-02-01 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReagentsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='products/%Y/%m/%d/')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.reagent', verbose_name='Медиафайлы для реагента')),
            ],
            options={
                'verbose_name': 'Медифайл для реагента',
                'verbose_name_plural': 'Медиафайлы для реагента',
            },
        ),
    ]
