# Generated by Django 3.1.5 on 2021-02-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_reagentsfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='photo',
            field=models.FileField(blank=True, upload_to='products/%Y/%m/%d/'),
        ),
    ]
