# Generated by Django 3.1.5 on 2021-02-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210217_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagentsfile',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='краткое описание к фото, не обязательно'),
        ),
        migrations.AddField(
            model_name='reagentsfile',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='название фото, не обязательно'),
        ),
    ]
