# Generated by Django 3.1.5 on 2021-02-21 15:12

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210217_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reagent',
            name='file',
        ),
        migrations.RemoveField(
            model_name='reagentsfile',
            name='media',
        ),
        migrations.AddField(
            model_name='reagent',
            name='main_photo',
            field=models.FileField(default=1, upload_to='products/%Y/%m/%d/', verbose_name='Фото для превью'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reagent',
            name='short_description',
            field=models.CharField(default=1, max_length=200, verbose_name='Краткое описание для превью'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reagentsfile',
            name='photo',
            field=models.FileField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='reagentsfile',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.reagent', verbose_name='Выбрать реагент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reagentsfile',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Видео с ютуба'),
        ),
        migrations.AlterField(
            model_name='reagentsfile',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='краткое описание к фото, не обязательно'),
        ),
    ]
