# Generated by Django 3.1.5 on 2021-02-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210221_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reagentsfile',
            name='name',
        ),
    ]
