# Generated by Django 3.1.5 on 2021-02-22 20:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_reagentsfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='slug',
            field=models.SlugField(default='afdfdf', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reagent',
            name='slug',
            field=models.SlugField(default=' fdfddf', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='division',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300, verbose_name='Описание направления'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='short_description',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='Краткое описание для превью'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Описание реагента'),
        ),
    ]
