# Generated by Django 3.1.5 on 2021-02-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210222_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='slug',
            field=models.SlugField(max_length=70, verbose_name='задать URL'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='slug',
            field=models.SlugField(max_length=70, verbose_name='задать URL'),
        ),
    ]
