# Generated by Django 3.1 on 2021-02-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210223_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='slug',
            field=models.SlugField(max_length=70, verbose_name='задать уникальный URL латинскими буквами, между словами дефис'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='slug',
            field=models.SlugField(max_length=70, verbose_name='задать уникальный URL латинскими буквами, между словами дефис'),
        ),
    ]
