# Generated by Django 3.1.7 on 2021-03-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='image',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='upload_time',
        ),
    ]
