# Generated by Django 3.1.7 on 2021-03-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0002_auto_20210306_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='file',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
