# Generated by Django 3.1.7 on 2021-03-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0006_auto_20210308_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='file',
            new_name='image',
        ),
    ]
