# Generated by Django 3.1.7 on 2021-03-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0008_auto_20210308_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='file',
            new_name='image',
        ),
    ]
