# Generated by Django 3.1.5 on 2021-02-01 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='about/%Y/%m/%d/')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.production', verbose_name='Фото производства')),
            ],
        ),
    ]
