# Generated by Django 3.1.5 on 2021-02-01 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_productionfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionfile',
            options={'verbose_name': 'Фото производства', 'verbose_name_plural': 'Фотографии производства'},
        ),
    ]
