# Generated by Django 3.1.5 on 2021-02-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20210211_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagephoto',
            name='title',
            field=models.CharField(default='fgfg', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainpagephoto',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
