# Generated by Django 3.1.5 on 2021-02-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20210212_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagephoto',
            name='photo',
            field=models.FileField(upload_to='static', verbose_name='фото'),
        ),
    ]
