# Generated by Django 3.1.5 on 2021-02-15 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20210212_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagephoto',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, verbose_name='слоган для фото на главной (не обязательно)'),
        ),
        migrations.AddField(
            model_name='productionfile',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='описание фотографии (не обязательно)'),
        ),
        migrations.AlterField(
            model_name='mainpagephoto',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='краткое описание для отображения на фото на главной (не обязательно)'),
        ),
        migrations.AlterField(
            model_name='mainpagephoto',
            name='photo',
            field=models.FileField(upload_to='uploads', verbose_name='фото'),
        ),
        migrations.CreateModel(
            name='LaboratoryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='описание фотографии (не обязательно)')),
                ('photo', models.FileField(upload_to='about/%Y/%m/%d/')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.laboratory', verbose_name='Фото лаборатории')),
            ],
            options={
                'verbose_name': 'Фото лаборатории',
                'verbose_name_plural': 'Фотографии лаборатории',
            },
        ),
    ]
