# Generated by Django 3.1.5 on 2021-02-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20210215_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratoryfile',
            name='laboratory',
        ),
        migrations.RemoveField(
            model_name='productionfile',
            name='production',
        ),
    ]
