# Generated by Django 3.1.5 on 2021-02-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_auto_20210215_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(max_length=25, verbose_name='Контактный телефон')),
                ('contact_phone2', models.CharField(blank=True, max_length=25, verbose_name='Контактный телефон-2')),
                ('contact_mail', models.EmailField(max_length=250, verbose_name='Контактная почта')),
                ('location', models.CharField(max_length=100, verbose_name='Адрес')),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'О компании',
                'verbose_name_plural': 'О компании',
            },
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
