# Generated by Django 3.1.5 on 2021-02-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_auto_20210216_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(blank=True, verbose_name='Описание компании')),
                ('photo', models.FileField(upload_to='about/%Y/%m/%d/', verbose_name='Фото компании')),
            ],
            options={
                'verbose_name': 'Описание и фото компании',
                'verbose_name_plural': 'Описание и фото компании',
            },
        ),
        migrations.DeleteModel(
            name='LaboratoryFile',
        ),
        migrations.DeleteModel(
            name='ProductionFile',
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AddField(
            model_name='laboratory',
            name='photo',
            field=models.FileField(default='1', upload_to='about/%Y/%m/%d/', verbose_name='Фото лаборатории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='photo',
            field=models.FileField(default='fdf', upload_to='about/%Y/%m/%d/', verbose_name='Фото производства'),
            preserve_default=False,
        ),
    ]
