# Generated by Django 3.1.5 on 2021-02-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_auto_20210218_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(verbose_name='Краткое описание компании для главной страницы')),
                ('photo', models.FileField(upload_to='uploads', verbose_name='фото для описания на главной странице')),
            ],
        ),
    ]
