# Generated by Django 3.1.5 on 2021-02-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_mainpagedescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpagedescription',
            options={'verbose_name': 'Краткое описание компании и картинка для главной страницы', 'verbose_name_plural': 'Краткие описания компании и картинки для главной страницы'},
        ),
        migrations.RemoveField(
            model_name='mainpagedescription',
            name='photo',
        ),
    ]
