# Generated by Django 3.1.5 on 2021-02-22 17:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_auto_20210222_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantages',
            name='adv',
            field=ckeditor.fields.RichTextField(verbose_name='Описание преимущества'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание компании'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='lab',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание лаборатории'),
        ),
        migrations.AlterField(
            model_name='mainpagedescription',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Краткое описание компании для главной страницы'),
        ),
        migrations.AlterField(
            model_name='production',
            name='production',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание производства'),
        ),
    ]
