# Generated by Django 3.1.5 on 2021-02-22 20:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_auto_20210222_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpagedescription',
            options={'verbose_name': 'Краткое описание компании главной страницы', 'verbose_name_plural': 'Краткие описания компании для главной страницы'},
        ),
        migrations.AlterField(
            model_name='advantages',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=100, verbose_name='Преимущество'),
        ),
    ]
